[package]
name = "orderbook"
version = "0.2.0"
authors = ["Åukasz Bednarski <lukasz@bednarski.me>"]
edition = "2021"
rust-version = "1.70"

[dependencies]
either = "1.13.0"
ordered-float = "4.2.2"
rustc-hash = "2.0.0"

[dev-dependencies]
rstest = "0.22.0"
